### PR TITLE
Set indent style to 2 indents

### PR DESCRIPTION
**Pull request by tsangste**
Links with https://github.com/tsangste/ChaosSpankr.Home/issues/7

### CODE REVIEW

**Comment by quickskape** [comment]
Should you format the indent on these files to two?

**Comment by tsangste** [comment]
yeah I was planning to get #9 in first before doing files changes to reduce conflicts

**Comment by quickskape** [comment]
Agreed. Do you want this merged? If so can you remove the 'do not merge' tag.
Then LGTM

**Comment by tsangste** [comment]
Going through files to set them to correct tabs first

**Pull request merged**
